//! Packet filter (pf) firewall management.

use crate::error::{Result, TunshareError};
use crate::system::run_cmd;
use std::fs;
use std::net::Ipv4Addr;
use std::path::Path;
use std::process::Command as SyncCommand;

const PF_CONF_PATH: &str = "/tmp/tunshare_pf.conf";
const DEFAULT_PF_CONF: &str = "/etc/pf.conf";
/// pf table of allowlisted destination IPs, populated by the resolver
/// before the DNS answer is sent so the first packet already matches.
pub const BYPASS_TABLE: &str = "tunshare_bypass";

/// WAN hop for allowlisted destinations. Traffic to `<tunshare_bypass>`
/// is NAT'd on this iface and `route-to`'d to this gateway.
#[derive(Debug, Clone)]
pub struct BypassConfig {
    pub wan_if: String,
    pub wan_gw: Ipv4Addr,
}

/// Manages pf firewall rules for VPN sharing.
pub struct Firewall {
    /// Whether we have active rules loaded.
    rules_loaded: bool,
    /// The config file path we're using.
    config_path: String,
}

impl Firewall {
    pub fn new() -> Self {
        Self {
            rules_loaded: false,
            config_path: PF_CONF_PATH.to_string(),
        }
    }

    /// Generate pf rules for NAT from LAN to VPN.
    /// Rules must be in order: options, normalization, translation, filtering
    ///
    /// We intentionally don't use "block all" because that would block the Mac's
    /// own connection to the VPN server, disconnecting the VPN when rules load.
    ///
    /// Note: NAT translation happens BEFORE filter rules, so outgoing filter rules
    /// must match the post-NAT source address (the VPN interface), not the original
    /// LAN address.
    ///
    /// `lan_ip` is the resolver bind address used by the DNS `rdr` (LAN
    /// clients with hardcoded 8.8.8.8 still land on us). `bypass` adds the
    /// WAN split-tunnel table + NAT/`route-to` when the allowlist is on.
    pub fn generate_rules(
        vpn_if: &str,
        lan_if: &str,
        lan_ip: Ipv4Addr,
        mss: u16,
        bypass: Option<&BypassConfig>,
    ) -> String {
        let (wan_macro, table_line, vpn_nat, extra_nat, extra_filter) = match bypass {
            Some(b) => (
                format!("wan_if = \"{}\"\nwan_gw = \"{}\"\n", b.wan_if, b.wan_gw),
                format!("table <{BYPASS_TABLE}> persist\n"),
                format!(
                    "nat on $ext_if inet from $int_if:network to ! <{BYPASS_TABLE}> -> ($ext_if) static-port"
                ),
                format!(
                    "nat on $wan_if inet from $int_if:network to <{BYPASS_TABLE}> -> ($wan_if) static-port\n"
                ),
                format!(
                    "pass in quick on $int_if route-to ($wan_if $wan_gw) inet from $int_if:network to <{BYPASS_TABLE}> keep state\npass out quick on $wan_if inet from ($wan_if) to any keep state\n"
                ),
            ),
            None => (
                String::new(),
                String::new(),
                "nat on $ext_if inet from $int_if:network to any -> ($ext_if) static-port"
                    .to_string(),
                String::new(),
                String::new(),
            ),
        };

        format!(
            r#"# VPN Sharing pf rules - generated by tunshare
# VPN interface: {vpn_if}
# LAN interface: {lan_if}

# 1. Options
set skip on lo0

ext_if = "{vpn_if}"
int_if = "{lan_if}"
{wan_macro}{table_line}
# 2. Normalization (must come before translation)
scrub in all no-df
scrub out on $ext_if inet proto tcp from $int_if:network to any max-mss {mss}

# 3. Translation
{vpn_nat}
{extra_nat}# Force LAN DNS (including hardcoded 8.8.8.8) onto the in-process resolver.
rdr on $int_if inet proto udp from $int_if:network to any port 53 -> {lan_ip}
rdr on $int_if inet proto tcp from $int_if:network to any port 53 -> {lan_ip}
rdr-anchor "natpmp"

# 4. Filtering
{extra_filter}# Allow all traffic on LAN interface (including DHCP from 0.0.0.0)
pass quick on $int_if all keep state
# Allow NAT'd traffic out (post-NAT, source is VPN interface address)
pass out quick on $ext_if inet from ($ext_if) to any keep state
anchor "natpmp"
"#
        )
    }

    /// Validate a pf configuration file.
    pub async fn validate_rules(config_path: &str) -> Result<()> {
        let output = run_cmd("pfctl", &["-n", "-f", config_path]).await?;

        let stderr = String::from_utf8_lossy(&output.stderr);

        // pfctl on macOS prints warnings to stderr even on success
        // Only treat as error if exit status is non-zero AND stderr contains actual errors
        if !output.status.success() {
            // Check for actual error indicators (not just warnings)
            let has_error = stderr.contains("syntax error")
                || stderr.contains("unknown")
                || stderr.contains("invalid")
                || stderr.contains("no valid")
                || (stderr.contains("error") && !stderr.contains("0 errors"));

            if has_error {
                return Err(TunshareError::FirewallError(format!(
                    "Rule validation failed: {}",
                    stderr.trim()
                )));
            }
        }

        Ok(())
    }

    /// Load pf rules from the generated config.
    ///
    /// `mss` is the IPv4 TCP MSS clamp for the scrub rule. Caller is
    /// expected to derive it from the active upstream's MTU
    /// (`ActiveUpstream::mss_v4()`) so the clamp tracks the tunnel.
    pub async fn load_rules(
        &mut self,
        vpn_if: &str,
        lan_if: &str,
        lan_ip: Ipv4Addr,
        mss: u16,
        bypass: Option<&BypassConfig>,
    ) -> Result<()> {
        let rules = Self::generate_rules(vpn_if, lan_if, lan_ip, mss, bypass);

        // Write to temp file
        fs::write(&self.config_path, &rules).map_err(TunshareError::Io)?;

        // Validate first
        Self::validate_rules(&self.config_path).await?;

        // Enable pf if not already enabled (best-effort)
        let _ = run_cmd("pfctl", &["-e"]).await;

        // Load the rules
        let output = run_cmd("pfctl", &["-f", &self.config_path]).await?;

        let stderr = String::from_utf8_lossy(&output.stderr);

        // pfctl on macOS prints warnings to stderr even on success
        // "Use of -f option, could disable the actions of the service" is just a warning
        // Only treat as error if there's an actual failure indicator
        if !output.status.success() {
            let is_just_warning = stderr.contains("Use of -f option")
                || stderr.contains("rules loaded")
                || stderr.contains("pf enabled");

            let stderr_lower = stderr.to_lowercase();
            let has_real_error = stderr_lower.contains("syntax error")
                || stderr_lower.contains("rules not loaded")
                || stderr.contains("unknown")
                || stderr.contains("invalid")
                || stderr.contains("no valid");

            if has_real_error && !is_just_warning {
                return Err(TunshareError::FirewallError(format!(
                    "Failed to load rules: {}",
                    stderr.trim()
                )));
            }
        }

        self.rules_loaded = true;
        Ok(())
    }

    /// Stop sharing and restore default pf rules (async wrapper).
    /// Delegates to `cleanup_sync` via `spawn_blocking`.
    pub async fn cleanup(&mut self) -> Result<()> {
        let config_path = self.config_path.clone();
        tokio::task::spawn_blocking(move || cleanup_sync_impl(&config_path))
            .await
            .map_err(|e| TunshareError::CommandFailed {
                command: "cleanup (spawn_blocking)".into(),
                message: e.to_string(),
            })??;

        self.rules_loaded = false;
        Ok(())
    }

    /// Get current pf rules (for debugging).
    /// Returns both NAT rules (-sn) and filter rules (-sr).
    pub async fn get_current_rules() -> Result<String> {
        let nat_output = run_cmd("pfctl", &["-sn"]).await?;
        let filter_output = run_cmd("pfctl", &["-sr"]).await?;

        let nat_rules = String::from_utf8_lossy(&nat_output.stdout);
        let filter_rules = String::from_utf8_lossy(&filter_output.stdout);

        let mut result = String::new();
        if !nat_rules.trim().is_empty() {
            result.push_str(&nat_rules);
        }
        if !filter_rules.trim().is_empty() {
            if !result.is_empty() {
                result.push('\n');
            }
            result.push_str(&filter_rules);
        }

        Ok(result)
    }

    /// Get current pf states (for debugging).
    pub async fn get_current_states() -> Result<String> {
        let output = run_cmd("pfctl", &["-ss"]).await?;
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    }

    /// Check if pf is enabled.
    pub async fn is_enabled() -> Result<bool> {
        let output = run_cmd("pfctl", &["-si"]).await?;
        let stdout = String::from_utf8_lossy(&output.stdout);
        Ok(stdout.contains("Status: Enabled"))
    }

    /// Synchronous cleanup for use in Drop and async wrapper.
    pub fn cleanup_sync(&mut self) {
        let _ = cleanup_sync_impl(&self.config_path);
        self.rules_loaded = false;
    }

    /// Insert IPv4s into the bypass table. No-op on empty. Must complete
    /// before the resolver returns the matching A records.
    pub fn table_add(ips: &[Ipv4Addr]) -> Result<()> {
        if ips.is_empty() {
            return Ok(());
        }
        let mut args = vec![
            "-t".to_string(),
            BYPASS_TABLE.to_string(),
            "-T".into(),
            "add".into(),
        ];
        args.extend(ips.iter().map(|ip| ip.to_string()));
        pfctl_table(&args)
    }

    /// Drop IPv4s from the bypass table (TTL eviction).
    pub fn table_delete(ips: &[Ipv4Addr]) -> Result<()> {
        if ips.is_empty() {
            return Ok(());
        }
        let mut args = vec![
            "-t".to_string(),
            BYPASS_TABLE.to_string(),
            "-T".into(),
            "delete".into(),
        ];
        args.extend(ips.iter().map(|ip| ip.to_string()));
        pfctl_table(&args)
    }

    /// Flush the bypass table. Best-effort: missing table is not an error.
    pub fn table_flush() {
        let _ = SyncCommand::new("pfctl")
            .args(["-t", BYPASS_TABLE, "-T", "flush"])
            .output();
    }
}

fn pfctl_table(args: &[String]) -> Result<()> {
    let output = SyncCommand::new("pfctl")
        .args(args)
        .output()
        .map_err(|error| TunshareError::CommandFailed {
            command: "pfctl table".into(),
            message: error.to_string(),
        })?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(TunshareError::FirewallError(format!(
            "pfctl -T failed: {}",
            stderr.trim()
        )));
    }
    Ok(())
}

impl Default for Firewall {
    fn default() -> Self {
        Self::new()
    }
}

impl Drop for Firewall {
    fn drop(&mut self) {
        // Attempt cleanup on drop, but don't panic on failure
        if self.rules_loaded {
            self.cleanup_sync();
        }
    }
}

/// Standalone sync cleanup logic. Single source of truth for both
/// `cleanup_sync()` and `cleanup()` (via `spawn_blocking`).
fn cleanup_sync_impl(config_path: &str) -> Result<()> {
    use std::process::Command as SyncCommand;

    let mut errors = Vec::new();

    // 1. Restore default pf rules (don't flush states - that kills VPN)
    if Path::new(DEFAULT_PF_CONF).exists() {
        let output = SyncCommand::new("pfctl")
            .args(["-f", DEFAULT_PF_CONF])
            .output();
        if let Ok(output) = output {
            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                if !stderr.contains("rules loaded") && stderr.contains("error") {
                    errors.push(format!("Failed to restore default rules: {}", stderr));
                }
            }
        }
    } else {
        let _ = SyncCommand::new("pfctl").args(["-d"]).output();
    }

    Firewall::table_flush();

    // 2. Remove our config file
    if Path::new(config_path).exists() {
        if let Err(e) = fs::remove_file(config_path) {
            errors.push(format!("Failed to remove config file: {}", e));
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(TunshareError::FirewallError(errors.join("; ")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_rules_always_redirects_dns() {
        let rules =
            Firewall::generate_rules("utun10", "en8", Ipv4Addr::new(192, 168, 2, 1), 1400, None);
        assert!(rules.contains(
            "rdr on $int_if inet proto udp from $int_if:network to any port 53 -> 192.168.2.1"
        ));
        assert!(rules.contains(
            "rdr on $int_if inet proto tcp from $int_if:network to any port 53 -> 192.168.2.1"
        ));
        assert!(rules
            .contains("nat on $ext_if inet from $int_if:network to any -> ($ext_if) static-port"));
        assert!(!rules.contains("tunshare_bypass"));
        assert!(!rules.contains("route-to"));
    }

    #[test]
    fn generate_rules_bypass_uses_wan_not_lan() {
        let bypass = BypassConfig {
            wan_if: "en0".into(),
            wan_gw: Ipv4Addr::new(192, 168, 1, 1),
        };
        let rules = Firewall::generate_rules(
            "utun10",
            "en8",
            Ipv4Addr::new(192, 168, 2, 1),
            1400,
            Some(&bypass),
        );
        assert!(rules.contains("table <tunshare_bypass> persist"));
        assert!(rules.contains("wan_if = \"en0\""));
        assert!(rules.contains("wan_gw = \"192.168.1.1\""));
        assert!(rules.contains("to ! <tunshare_bypass>"));
        assert!(rules.contains("nat on $wan_if inet from $int_if:network to <tunshare_bypass>"));
        // Apple pf wants route-to after `on $if` and before `from`. OpenBSD
        // `from … to … route-to` is a syntax error at load time.
        assert!(rules.contains(
            "pass in quick on $int_if route-to ($wan_if $wan_gw) inet from $int_if:network to <tunshare_bypass> keep state"
        ));
        assert!(!rules.contains("to <tunshare_bypass> route-to"));
        assert!(!rules.contains("route-to ($int_if"));
    }
}
